-- Generated by nwg-displays on 2026-08-03 at 22:38:49. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@59.95",
    position = "3165x363",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "2085x363",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@60.0",
    position = "5725x723",
    scale = 1.0
})
