#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

# Starship prompt (overrides PS1 above when installed)
command -v starship >/dev/null 2>&1 && eval "$(starship init bash)"
